import { Item } from '../../types/item';

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'seed-1',
    url: 'https://go.dev/doc/effective_go',
    title: 'Effective Go: Советы по написанию чистого и идиоматичного кода на Go',
    description: 'Руководство по написанию выразительного и идиоматичного кода на Go: форматирование, соглашения об именовании, структуры данных и конкурентность.',
    siteName: 'Go.dev',
    author: 'Авторы Go',
    type: 'documentation',
    status: 'inbox',
    isFavorite: true,
    tags: [
      { id: 'tag-go', name: 'go' },
      { id: 'tag-prog', name: 'programming' },
    ],
    notes: 'Разобраться с context.Context.\nОсобенно интересуют:\n- cancellation\n- timeout\n- deadline',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-2',
    url: 'https://github.com/golang/go',
    title: 'golang/go: Исходный код языка программирования Go',
    description: 'Официальный репозиторий языка Go: компилятор, runtime, стандартная библиотека и инструменты.',
    siteName: 'GitHub',
    author: 'golang',
    type: 'github',
    status: 'inbox',
    isFavorite: false,
    tags: [
      { id: 'tag-go', name: 'go' },
      { id: 'tag-github', name: 'github' },
    ],
    notes: 'Посмотреть реализацию sync.Pool и runtime memory allocator.',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-3',
    url: 'https://www.youtube.com/watch?v=vYp4LYbnnW8',
    title: 'Raft: Алгоритм консенсуса для распределённых систем',
    description: 'Наглядное и интуитивное объяснение алгоритма консенсуса Raft: выборы лидера, репликация лога и гарантии безопасности.',
    siteName: 'YouTube',
    author: 'Diego Ongaro & John Ousterhout',
    type: 'video',
    status: 'inbox',
    isFavorite: true,
    tags: [
      { id: 'tag-network', name: 'network' },
      { id: 'tag-dist', name: 'distributed' },
    ],
    notes: 'Отличный визуальный разбор. Сравнить с Paxos и zab protocol.',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-4',
    url: 'https://docs.kernel.org/networking/packet_mmap.html',
    title: 'Linux Kernel Networking: Packet MMAP и сетевые буферы',
    description: 'Packet MMAP используется для повышения производительности захвата и передачи сетевых пакетов в сетевом стеке ядра Linux.',
    siteName: 'Linux Docs',
    author: 'Linux Kernel Documentation',
    type: 'documentation',
    status: 'inbox',
    isFavorite: false,
    tags: [
      { id: 'tag-linux', name: 'linux' },
      { id: 'tag-network', name: 'network' },
    ],
    notes: 'Кольцевые буферы SKB и zero-copy передача пакетов через AF_PACKET.',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-5',
    url: 'https://blog.pragmaticengineer.com/scaling-engineering-teams/',
    title: 'Масштабирование инженерных команд: уроки гиперроста',
    description: 'Как структурировать команды, сохранять скорость разработки, управлять техдолгом и поддерживать инженерную культуру при быстром росте.',
    siteName: 'The Pragmatic Engineer',
    author: 'Gergely Orosz',
    type: 'article',
    status: 'reading',
    isFavorite: true,
    tags: [
      { id: 'tag-eng', name: 'engineering' },
      { id: 'tag-leadership', name: 'leadership' },
    ],
    notes: 'Хороший раздел про RFC-процессы и децентрализацию архитектурных решений.',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-6',
    url: 'https://docker.com/blog/how-docker-networking-works/',
    title: 'Сетевой стек Docker под капотом: Bridge, Host и Overlay',
    description: 'Глубокий разбор сетевых пространств имён Linux (network namespaces), таблиц iptables NAT, виртуальных veth-пар и bridge-устройств.',
    siteName: 'Docker',
    author: 'Docker Engineering',
    type: 'article',
    status: 'completed',
    isFavorite: false,
    tags: [
      { id: 'tag-docker', name: 'docker' },
      { id: 'tag-network', name: 'network' },
      { id: 'tag-linux', name: 'linux' },
    ],
    notes: 'Понял, как работают veth-пары и br_netfilter. Проверено на локальном Ubuntu хосте.',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    readAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-7',
    url: 'https://doc.rust-lang.org/book/ch09-00-error-handling.html',
    title: 'Язык Rust: Глава 9. Обработка ошибок',
    description: 'В Rust ошибки делятся на две основные категории: восстановимые и невосстановимые. Изучение Result<T, E> и макроса panic!.',
    siteName: 'Rust Book',
    author: 'Steve Klabnik and Carol Nichols',
    type: 'documentation',
    status: 'completed',
    isFavorite: true,
    tags: [
      { id: 'tag-rust', name: 'rust' },
      { id: 'tag-prog', name: 'programming' },
    ],
    notes: 'Оператор ? и трейт From для удобного проброса ошибок вверх по стеку вызовов.',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    readAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-8',
    url: 'https://news.ycombinator.com/item?id=39100000',
    title: 'Show HN: Создание распределённого хранилища событий на Go с низкой задержкой',
    description: 'Обсуждение архитектуры: write-ahead logs, компромиссы fsync и насыщение SSD IOPS при обработке 1 миллиона событий в секунду.',
    siteName: 'Hacker News',
    author: 'dang',
    type: 'news',
    status: 'archived',
    isFavorite: false,
    tags: [
      { id: 'tag-go', name: 'go' },
      { id: 'tag-dist', name: 'distributed' },
    ],
    notes: 'Архивировано. Основные выводы выписаны в рабочий Notion.',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
